globals

/* COMMON */

integer SPELL_Talent_F = 'A0A4'
integer SPELL_Talent_C = 'A0A1'
integer SPELL_Talent_V = 'A0A5'

integer SPELL_Talent_Eagle_Eye = 'A0EZ'
integer SPELL_Talent_Charge = 'A0EY'
integer SPELL_Talent_Jump = 'S006'
integer SPELL_Talent_Ghost_Walk = 'A0F0'

integer SPELL_Talent_Heroic_Swordsmen = 'A0A6'
integer SPELL_Talent_Aim = 'A0BF'
integer SPELL_Talent_Aura_Leaf = 'A0C1'
integer SPELL_Talent_Source_Vitality = 'A0ET'

integer SPELL_Talent_Hepatoenteral_Fracture = 'A0EU'
integer SPELL_Talent_Holy_Sword = 'A0EV'
integer SPELL_Talent_Crusade = 'A0EW'
integer SPELL_Talent_Snow_Frost = 'A0EX'

boolean array SPELL_Talent_F_isLearn
boolean array SPELL_Talent_C_isLearn
boolean array SPELL_Talent_V_isLearn

/* 地穴甲虫 */
//NORMAL
integer SPELL_SHITF_CRYPTBEETLE_Q_NORMAL_CHUANCI = 'A017'			//穿刺
integer SPELL_SHITF_CRYPTBEETLE_W_NORMAL_ZUANDI = 'A02I'			//钻地
integer SPELL_SHITF_CRYPTBEETLE_E_NORMAL_FUSHICHONGYE = 'A02J'		//腐蚀虫液
integer SPELL_SHITF_CRYPTBEETLE_R_NORMAL_TUIKE = 'A02L'				//蜕壳
integer SPELL_SHITF_CRYPTBEETLE_D_NORMAL_JIANCIWAIKE = 'A030'		//尖刺外壳
//CRAZY
integer SPELL_SHITF_CRYPTBEETLE_Q_CRAZY_CHUANCI = 'A0CS'		//穿刺
integer SPELL_SHITF_CRYPTBEETLE_W_CRAZY_ZUANDI = 'A02I'			//钻地
integer SPELL_SHITF_CRYPTBEETLE_E_CRAZY_FUSHICHONGYE = 'A02J'	//腐蚀虫液
integer SPELL_SHITF_CRYPTBEETLE_R_CRAZY_TUIKE = 'A02L'				//蜕壳
integer SPELL_SHITF_CRYPTBEETLE_D_CRAZY_JIANCIWAIKE = 'A030'		//尖刺外壳
//GOD
integer SPELL_SHITF_CRYPTBEETLE_Q_GOD_CHUANCI = 'A0CT'			//穿刺
integer SPELL_SHITF_CRYPTBEETLE_W_GOD_ZUANDI = 'A0CU'			//钻地
integer SPELL_SHITF_CRYPTBEETLE_E_GOD_FUSHICHONGYE = 'A02J'		//腐蚀虫液
integer SPELL_SHITF_CRYPTBEETLE_R_GOD_TUIKE = 'A0CV'				//蜕壳
integer SPELL_SHITF_CRYPTBEETLE_D_GOD_JIANCIWAIKE = 'A0CW'		//尖刺外壳
//FIGHT



/* 影刺客 */
//NORMAL
integer SPELL_SHITF_ARCANEHUNTER_Q_NORMAL_TUXI = 'A02M'				//突袭
integer SPELL_SHITF_ARCANEHUNTER_W_NORMAL_SHABEI = 'A02N'				//杀背
integer SPELL_SHITF_ARCANEHUNTER_E_NORMAL_ANSHALINGYU = 'A02P'		//暗杀领域
integer SPELL_SHITF_ARCANEHUNTER_R_NORMAL_TIANZHU = 'A02Q'			//天诛
integer SPELL_SHITF_ARCANEHUNTER_D_NORMAL_JIYEHEIYING = 'A02R'		//极夜黑影
//CRAZY
integer SPELL_SHITF_ARCANEHUNTER_Q_CRAZY_TUXI = 'A0CY'				//突袭
integer SPELL_SHITF_ARCANEHUNTER_W_CRAZY_SHABEI = 'A0D0'			//杀背
integer SPELL_SHITF_ARCANEHUNTER_E_CRAZY_ANSHALINGYU = 'A0EF'		//暗杀领域
integer SPELL_SHITF_ARCANEHUNTER_R_CRAZY_TIANZHU = 'A0EE'			//天诛
integer SPELL_SHITF_ARCANEHUNTER_D_CRAZY_JIYEHEIYING = 'A0D2'		//极夜黑影
//GOD
integer SPELL_SHITF_ARCANEHUNTER_Q_GOD_TUXI = 'A02M'				//突袭
integer SPELL_SHITF_ARCANEHUNTER_W_GOD_SHABEI = 'A02N'			//杀背
integer SPELL_SHITF_ARCANEHUNTER_E_GOD_ANSHALINGYU = 'A02P'		//暗杀领域
integer SPELL_SHITF_ARCANEHUNTER_R_GOD_TIANZHU = 'A02Q'			//天诛
integer SPELL_SHITF_ARCANEHUNTER_D_GOD_JIYEHEIYING = 'A02R'		//极夜黑影
//FIGHT



/* 恶魔猎手 */
//NORMAL
integer SPELL_SHITF_DEMONHUNTER_Q_NORMAL_EGUI = 'A03A'						//恶鬼
integer SPELL_SHITF_DEMONHUNTER_W_NORMAL_HENNIANCHANSHEN = 'A03B'		//恨念缠身
integer SPELL_SHITF_DEMONHUNTER_E_NORMAL_GUIYING = 'A03M'					//鬼影
integer SPELL_SHITF_DEMONHUNTER_R_NORMAL_GUIYINGCHONGCHONG = 'A03N'		//鬼影重重
integer SPELL_SHITF_DEMONHUNTER_D_NORMAL_CANYINGQIEGE = 'A03Q'				//残影切割
//CRAZY
integer SPELL_SHITF_DEMONHUNTER_Q_CRAZY_EGUI = 'A0D3'						//恶鬼
integer SPELL_SHITF_DEMONHUNTER_W_CRAZY_HENNIANCHANSHEN = 'A03B'		//恨念缠身
integer SPELL_SHITF_DEMONHUNTER_E_CRAZY_GUIYING = 'A0D7'					//鬼影
integer SPELL_SHITF_DEMONHUNTER_R_CRAZY_GUIYINGCHONGCHONG = 'A0D8'	//鬼影重重
integer SPELL_SHITF_DEMONHUNTER_D_CRAZY_CANYINGQIEGE = 'A0EL'			//残影切割
//GOD
integer SPELL_SHITF_DEMONHUNTER_Q_GOD_EGUI = 'A0D5'						//恶鬼
integer SPELL_SHITF_DEMONHUNTER_W_GOD_HENNIANCHANSHEN = 'A0D6'		//恨念缠身
integer SPELL_SHITF_DEMONHUNTER_E_GOD_GUIYING = 'A03M'					//鬼影
integer SPELL_SHITF_DEMONHUNTER_R_GOD_GUIYINGCHONGCHONG = 'A03N'		//鬼影重重
integer SPELL_SHITF_DEMONHUNTER_D_GOD_CANYINGQIEGE = 'A03Q'				//残影切割
//FIGHT



/* 无双 */
//NORMAL
integer SPELL_SHITF_UNPARALLELED_Q_NORMAL_HUOYANLIANZHAN = 'A03U'		//火焰连斩
integer SPELL_SHITF_UNPARALLELED_W_NORMAL_WEIWU = 'A03Y'					//威武
integer SPELL_SHITF_UNPARALLELED_E_NORMAL_TIANXIAWUSHUANG = 'A03Z'		//天下无双
integer SPELL_SHITF_UNPARALLELED_R_NORMAL_QIANJUNPO = 'A041'				//千军破
integer SPELL_SHITF_UNPARALLELED_D_NORMAL_HUOQILUANWU = 'A042'			//火气乱舞
//CRAZY
integer SPELL_SHITF_UNPARALLELED_Q_CRAZY_HUOYANLIANZHAN = 'A0D9'		//火焰连斩
integer SPELL_SHITF_UNPARALLELED_W_CRAZY_WEIWU = 'A03Y'					//威武
integer SPELL_SHITF_UNPARALLELED_E_CRAZY_TIANXIAWUSHUANG = 'A0DB'		//天下无双
integer SPELL_SHITF_UNPARALLELED_R_CRAZY_QIANJUNPO = 'A0DC'				//千军破
integer SPELL_SHITF_UNPARALLELED_D_CRAZY_HUOQILUANWU = 'A042'			//火气乱舞
//GOD
integer SPELL_SHITF_UNPARALLELED_Q_GOD_HUOYANLIANZHAN = 'A0DA'		//火焰连斩
integer SPELL_SHITF_UNPARALLELED_W_GOD_WEIWU = 'A03Y'					//威武
integer SPELL_SHITF_UNPARALLELED_E_GOD_TIANXIAWUSHUANG = 'A03Z'		//天下无双
integer SPELL_SHITF_UNPARALLELED_R_GOD_QIANJUNPO = 'A0DD'				//千军破
integer SPELL_SHITF_UNPARALLELED_D_GOD_HUOQILUANWU = 'A042'			//火气乱舞
//FIGHT



/* 暗杀者 */
//NORMAL
integer SPELL_SHITF_ASSASSIN_Q_NORMAL_FENSHEN = 'A048'			//分身
integer SPELL_SHITF_ASSASSIN_W_NORMAL_SHOUSHUO = 'A043'		//闪烁
integer SPELL_SHITF_ASSASSIN_E_NORMAL_QIANGLIEGONGJI = 'A045'	//强烈攻击
integer SPELL_SHITF_ASSASSIN_R_NORMAL_SHUNSHAXIULIAN = 'A044'	//瞬杀修炼
integer SPELL_SHITF_ASSASSIN_D_NORMAL_YIJI = 'A046'				//一击
//CRAZY
integer SPELL_SHITF_ASSASSIN_Q_CRAZY_FENSHEN = 'A048'			//分身
integer SPELL_SHITF_ASSASSIN_W_CRAZY_SHOUSHUO = 'A043'			//闪烁
integer SPELL_SHITF_ASSASSIN_E_CRAZY_QIANGLIEGONGJI = 'A0DE'		//强烈攻击
integer SPELL_SHITF_ASSASSIN_R_CRAZY_SHUNSHAXIULIAN = 'A0DF'	//瞬杀修炼
integer SPELL_SHITF_ASSASSIN_D_CRAZY_YIJI = 'A0DG'					//一击
//GOD
integer SPELL_SHITF_ASSASSIN_Q_GOD_FENSHEN = 'A048'			//分身
integer SPELL_SHITF_ASSASSIN_W_GOD_SHOUSHUO = 'A043'		//闪烁
integer SPELL_SHITF_ASSASSIN_E_GOD_QIANGLIEGONGJI = 'A045'	//强烈攻击
integer SPELL_SHITF_ASSASSIN_R_GOD_SHUNSHAXIULIAN = 'A044'	//瞬杀修炼
integer SPELL_SHITF_ASSASSIN_D_GOD_YIJI = 'A0DH'				//一击
//FIGHT



/* 逸风 */
//NORMAL
integer SPELL_SHITF_WIND_Q_NORMAL_YICHA = 'A00W'				//一刹
integer SPELL_SHITF_WIND_W_NORMAL_XUNSHOU = 'A0AV'			//迅手
integer SPELL_SHITF_WIND_E_NORMAL_WUYINGZHAN = 'A0AW'		//无影斩
integer SPELL_SHITF_WIND_R_NORMAL_WUYINGZHANFENG = 'A0AX'	//无影斩风
integer SPELL_SHITF_WIND_D_NORMAL_JIJIJIANSHA = 'A0B3'			//疾疾剑刹
//CRAZY
integer SPELL_SHITF_WIND_Q_CRAZY_YICHA = 'A0DI'				//一刹
integer SPELL_SHITF_WIND_W_CRAZY_XUNSHOU = 'A0AV'			//迅手
integer SPELL_SHITF_WIND_E_CRAZY_WUYINGZHAN = 'A0AW'		//无影斩
integer SPELL_SHITF_WIND_R_CRAZY_WUYINGZHANFENG = 'A0DL'	//无影斩风
integer SPELL_SHITF_WIND_D_CRAZY_JIJIJIANSHA = 'A0EO'			//疾疾剑刹
//GOD
integer SPELL_SHITF_WIND_Q_GOD_YICHA = 'A0DJ'					//一刹
integer SPELL_SHITF_WIND_W_GOD_XUNSHOU = 'A0AV'			//迅手
integer SPELL_SHITF_WIND_E_GOD_WUYINGZHAN = 'A0DK'			//无影斩
integer SPELL_SHITF_WIND_R_GOD_WUYINGZHANFENG = 'A0DM'	//无影斩风
integer SPELL_SHITF_WIND_D_GOD_JIJIJIANSHA = 'A0B3'			//疾疾剑刹
//FIGHT



/* 霹雳 */
//NORMAL
integer SPELL_SHITF_THUNDERBOLT_Q_NORMAL_DIANGUANGHUOSHI = 'A04A'	//电光火石
integer SPELL_SHITF_THUNDERBOLT_W_NORMAL_JINGXIAPILI = 'A04B'			//惊吓霹雳
integer SPELL_SHITF_THUNDERBOLT_E_NORMAL_LIZICHONGNENG = 'A04F'		//离子充能
integer SPELL_SHITF_THUNDERBOLT_R_NORMAL_DIANCHUANDAO = 'A04H'		//电传导
integer SPELL_SHITF_THUNDERBOLT_D_NORMAL_LEIQU = 'A04I'					//雷区
//CRAZY
integer SPELL_SHITF_THUNDERBOLT_Q_CRAZY_DIANGUANGHUOSHI = 'A0DO'	//电光火石
integer SPELL_SHITF_THUNDERBOLT_W_CRAZY_JINGXIAPILI = 'A0DP'			//惊吓霹雳
integer SPELL_SHITF_THUNDERBOLT_E_CRAZY_LIZICHONGNENG = 'A04F'		//离子充能
integer SPELL_SHITF_THUNDERBOLT_R_CRAZY_DIANCHUANDAO = 'A04H'		//电传导
integer SPELL_SHITF_THUNDERBOLT_D_CRAZY_LEIQU = 'A04I'					//雷区
//GOD
integer SPELL_SHITF_THUNDERBOLT_Q_GOD_DIANGUANGHUOSHI = 'A04A'	//电光火石
integer SPELL_SHITF_THUNDERBOLT_W_GOD_JINGXIAPILI = 'A0DQ'			//惊吓霹雳
integer SPELL_SHITF_THUNDERBOLT_E_GOD_LIZICHONGNENG = 'A04F'		//离子充能
integer SPELL_SHITF_THUNDERBOLT_R_GOD_DIANCHUANDAO = 'A04H'		//电传导
integer SPELL_SHITF_THUNDERBOLT_D_GOD_LEIQU = 'A04I'					//雷区
//FIGHT



/* 召唤师 */
//NORMAL
integer SPELL_SHITF_KAEL_Q_NORMAL_MINGXIANG = 'A058'			//冥想
integer SPELL_SHITF_KAEL_W_NORMAL_XIANJIJINGLING = 'A05W'		//献祭精灵
integer SPELL_SHITF_KAEL_E_NORMAL_WANGZHEHUSHENG = 'A05Y'	//亡者呼声
integer SPELL_SHITF_KAEL_R_NORMAL_YINIANZUZHOU = 'A061'			//意念诅咒
integer SPELL_SHITF_KAEL_D_NORMAL_KONGMING = 'A064'			//空冥
//CRAZY
integer SPELL_SHITF_KAEL_Q_CRAZY_MINGXIANG = 'A058'			//冥想
integer SPELL_SHITF_KAEL_W_CRAZY_XIANJIJINGLING = 'A05W'		//献祭精灵
integer SPELL_SHITF_KAEL_E_CRAZY_WANGZHEHUSHENG = 'A05Y'	//亡者呼声
integer SPELL_SHITF_KAEL_R_CRAZY_YINIANZUZHOU = 'A061'		//意念诅咒
integer SPELL_SHITF_KAEL_D_CRAZY_KONGMING = 'A064'			//空冥
//GOD
integer SPELL_SHITF_KAEL_Q_GOD_MINGXIANG = 'A058'			//冥想
integer SPELL_SHITF_KAEL_W_GOD_XIANJIJINGLING = 'A05W'		//献祭精灵
integer SPELL_SHITF_KAEL_E_GOD_WANGZHEHUSHENG = 'A0DR'	//亡者呼声
integer SPELL_SHITF_KAEL_R_GOD_YINIANZUZHOU = 'A061'			//意念诅咒
integer SPELL_SHITF_KAEL_D_GOD_KONGMING = 'A064'				//空冥
//FIGHT



/* 德鲁伊法尔 */
//NORMAL
integer SPELL_SHITF_DRUIDfARRE_Q_NORMAL_ZHILIAOBO = 'A06F'			//治疗波
integer SPELL_SHITF_DRUIDfARRE_W_NORMAL_SHENSHENGPILI = 'A065'	//神圣霹雳
integer SPELL_SHITF_DRUIDfARRE_E_NORMAL_CHENGFENG = 'A068'			//乘风
integer SPELL_SHITF_DRUIDfARRE_R_NORMAL_ZHIHUIZHILI = 'A06D'			//智慧之力
integer SPELL_SHITF_DRUIDfARRE_D_NORMAL_HUIGUI = 'A06I'				//回归
//CRAZY
integer SPELL_SHITF_DRUIDfARRE_Q_CRAZY_ZHILIAOBO = 'A06F'			//治疗波
integer SPELL_SHITF_DRUIDfARRE_W_CRAZY_SHENSHENGPILI = 'A065'		//神圣霹雳
integer SPELL_SHITF_DRUIDfARRE_E_CRAZY_CHENGFENG = 'A068'			//乘风
integer SPELL_SHITF_DRUIDfARRE_R_CRAZY_ZHIHUIZHILI = 'A06D'			//智慧之力
integer SPELL_SHITF_DRUIDfARRE_D_CRAZY_HUIGUI = 'A06I'				//回归
//GOD
integer SPELL_SHITF_DRUIDfARRE_Q_GOD_ZHILIAOBO = 'A06F'			//治疗波
integer SPELL_SHITF_DRUIDfARRE_W_GOD_SHENSHENGPILI = 'A065'		//神圣霹雳
integer SPELL_SHITF_DRUIDfARRE_E_GOD_CHENGFENG = 'A068'			//乘风
integer SPELL_SHITF_DRUIDfARRE_R_GOD_ZHIHUIZHILI = 'A06D'			//智慧之力
integer SPELL_SHITF_DRUIDfARRE_D_GOD_HUIGUI = 'A0DS'				//回归
//FIGHT



/* 美杜莎 */
//NORMAL
integer SPELL_SHITF_MEDUSA_Q_NORMAL_BINGHANZHISHI = 'A06Z'	//冰寒之矢
integer SPELL_SHITF_MEDUSA_W_NORMAL_SHUIYAOZHIBI = 'A07F'		//水妖之壁
integer SPELL_SHITF_MEDUSA_E_NORMAL_SHUIHUAZHIWU = 'A073'		//水花之舞
integer SPELL_SHITF_MEDUSA_R_NORMAL_MIWUSHIHUA = 'A07B'		//迷雾石化
integer SPELL_SHITF_MEDUSA_D_NORMAL_SHENHAIHEXIN = 'A06U'		//深海核心
//CRAZY
integer SPELL_SHITF_MEDUSA_Q_CRAZY_BINGHANZHISHI = 'A06Z'		//冰寒之矢
integer SPELL_SHITF_MEDUSA_W_CRAZY_SHUIYAOZHIBI = 'A07F'		//水妖之壁
integer SPELL_SHITF_MEDUSA_E_CRAZY_SHUIHUAZHIWU = 'A073'		//水花之舞
integer SPELL_SHITF_MEDUSA_R_CRAZY_MIWUSHIHUA = 'A0DU'		//迷雾石化
integer SPELL_SHITF_MEDUSA_D_CRAZY_SHENHAIHEXIN = 'A0DW'		//深海核心
//GOD
integer SPELL_SHITF_MEDUSA_Q_GOD_BINGHANZHISHI = 'A0DT'	//冰寒之矢
integer SPELL_SHITF_MEDUSA_W_GOD_SHUIYAOZHIBI = 'A07F'		//水妖之壁
integer SPELL_SHITF_MEDUSA_E_GOD_SHUIHUAZHIWU = 'A073'		//水花之舞
integer SPELL_SHITF_MEDUSA_R_GOD_MIWUSHIHUA = 'A0DV'		//迷雾石化
integer SPELL_SHITF_MEDUSA_D_GOD_SHENHAIHEXIN = 'A06U'		//深海核心
//FIGHT



/* 山丘之王 */
//NORMAL
integer SPELL_SHITF_MOUNTAINKING_Q_NORMAL_WUXINGZHICHUI = 'A087'	//无形之锤
integer SPELL_SHITF_MOUNTAINKING_W_NORMAL_CHUIJI = 'A088'				//锤击
integer SPELL_SHITF_MOUNTAINKING_E_NORMAL_BUFANZHONGJI = 'A089'		//不凡重击
integer SPELL_SHITF_MOUNTAINKING_R_NORMAL_TIANSHENXIAFAN = 'A085'	//天神下凡
integer SPELL_SHITF_MOUNTAINKING_D_NORMAL_LIANCHUIWU = 'A083'		//连锤舞
//CRAZY
integer SPELL_SHITF_MOUNTAINKING_Q_CRAZY_WUXINGZHICHUI = 'A087'	//无形之锤
integer SPELL_SHITF_MOUNTAINKING_W_CRAZY_CHUIJI = 'A088'			//锤击
integer SPELL_SHITF_MOUNTAINKING_E_CRAZY_BUFANZHONGJI = 'A089'	//不凡重击
integer SPELL_SHITF_MOUNTAINKING_R_CRAZY_TIANSHENXIAFAN = 'A085'	//天神下凡
integer SPELL_SHITF_MOUNTAINKING_D_CRAZY_LIANCHUIWU = 'A0DX'		//连锤舞
//GOD
integer SPELL_SHITF_MOUNTAINKING_Q_GOD_WUXINGZHICHUI = 'A087'	//无形之锤
integer SPELL_SHITF_MOUNTAINKING_W_GOD_CHUIJI = 'A088'				//锤击
integer SPELL_SHITF_MOUNTAINKING_E_GOD_BUFANZHONGJI = 'A089'		//不凡重击
integer SPELL_SHITF_MOUNTAINKING_R_GOD_TIANSHENXIAFAN = 'A085'	//天神下凡
integer SPELL_SHITF_MOUNTAINKING_D_GOD_LIANCHUIWU = 'A0DY'		//连锤舞
//FIGHT



/* 捍卫骑士 */
//NORMAL
integer SPELL_SHITF_PROTECTKNIGHT_Q_NORMAL_YUSHU = 'A092'					//愈术
integer SPELL_SHITF_PROTECTKNIGHT_W_NORMAL_SHOUWEILINGYU = 'A08T'		//守卫领域
integer SPELL_SHITF_PROTECTKNIGHT_E_NORMAL_ZHANZHENGHAOJIAO = 'A08W'	//战争号角
integer SPELL_SHITF_PROTECTKNIGHT_R_NORMAL_GUANGMINGPAO = 'A08S'		//光明炮
integer SPELL_SHITF_PROTECTKNIGHT_D_NORMAL_SHENGGUANGZHU = 'A09E'		//圣光柱
//CRAZY
integer SPELL_SHITF_PROTECTKNIGHT_Q_CRAZY_YUSHU = 'A092'					//愈术
integer SPELL_SHITF_PROTECTKNIGHT_W_CRAZY_SHOUWEILINGYU = 'A08T'			//守卫领域
integer SPELL_SHITF_PROTECTKNIGHT_E_CRAZY_ZHANZHENGHAOJIAO = 'A08W'		//战争号角
integer SPELL_SHITF_PROTECTKNIGHT_R_CRAZY_GUANGMINGPAO = 'A0DZ'			//光明炮
integer SPELL_SHITF_PROTECTKNIGHT_D_CRAZY_SHENGGUANGZHU = 'A0EQ'		//圣光柱
//GOD
integer SPELL_SHITF_PROTECTKNIGHT_Q_GOD_YUSHU = 'A092'					//愈术
integer SPELL_SHITF_PROTECTKNIGHT_W_GOD_SHOUWEILINGYU = 'A08T'		//守卫领域
integer SPELL_SHITF_PROTECTKNIGHT_E_GOD_ZHANZHENGHAOJIAO = 'A08W'	//战争号角
integer SPELL_SHITF_PROTECTKNIGHT_R_GOD_GUANGMINGPAO = 'A0E0'		//光明炮
integer SPELL_SHITF_PROTECTKNIGHT_D_GOD_SHENGGUANGZHU = 'A0E1'		//圣光柱
//FIGHT



/* 撼地蛮牛 */
//NORMAL
integer SPELL_SHITF_SHAKEBULL_Q_NORMAL_JIANTA = 'A09I'			//践踏
integer SPELL_SHITF_SHAKEBULL_W_NORMAL_TUWEI = 'A09K'			//突围
integer SPELL_SHITF_SHAKEBULL_E_NORMAL_ZHENDANGBO = 'A09L'	//震荡波
integer SPELL_SHITF_SHAKEBULL_R_NORMAL_CANYINGTA = 'A09J'		//残影踏
integer SPELL_SHITF_SHAKEBULL_D_NORMAL_ZHENHANDADI = 'A0AE'	//震撼大地
//CRAZY
integer SPELL_SHITF_SHAKEBULL_Q_CRAZY_JIANTA = 'A09I'			//践踏
integer SPELL_SHITF_SHAKEBULL_W_CRAZY_TUWEI = 'A09K'			//突围
integer SPELL_SHITF_SHAKEBULL_E_CRAZY_ZHENDANGBO = 'A0E4'	//震荡波
integer SPELL_SHITF_SHAKEBULL_R_CRAZY_CANYINGTA = 'A0E6'	//残影踏
integer SPELL_SHITF_SHAKEBULL_D_CRAZY_ZHENHANDADI = 'A0E8'	//震撼大地
//GOD
integer SPELL_SHITF_SHAKEBULL_Q_GOD_JIANTA = 'A0E2'			//践踏
integer SPELL_SHITF_SHAKEBULL_W_GOD_TUWEI = 'A09K'			//突围
integer SPELL_SHITF_SHAKEBULL_E_GOD_ZHENDANGBO = 'A0E5'	//震荡波
integer SPELL_SHITF_SHAKEBULL_R_GOD_CANYINGTA = 'A0E7'		//残影踏
integer SPELL_SHITF_SHAKEBULL_D_GOD_ZHENHANDADI = 'A0E9'	//震撼大地
//FIGHT



/* 死亡骑士 */
//NORMAL
integer SPELL_SHITF_DEATHKNIGHT_Q_NORMAL_YUANQIZHAN = 'A0AH'		//怨气斩
integer SPELL_SHITF_DEATHKNIGHT_W_NORMAL_JIUSHU = 'A0AI'				//救赎
integer SPELL_SHITF_DEATHKNIGHT_E_NORMAL_FANKANGMINGYUN = 'A0AQ'	//反抗命运
integer SPELL_SHITF_DEATHKNIGHT_R_NORMAL_HUIGUANGFANZHAO = 'A0AS'	//回光返照
integer SPELL_SHITF_DEATHKNIGHT_D_NORMAL_DUOLUO = 'A0AY'				//堕落
//CRAZY
integer SPELL_SHITF_DEATHKNIGHT_Q_CRAZY_YUANQIZHAN = 'A0AH'			//怨气斩
integer SPELL_SHITF_DEATHKNIGHT_W_CRAZY_JIUSHU = 'A0AI'					//救赎
integer SPELL_SHITF_DEATHKNIGHT_E_CRAZY_FANKANGMINGYUN = 'A0AQ'		//反抗命运
integer SPELL_SHITF_DEATHKNIGHT_R_CRAZY_HUIGUANGFANZHAO = 'A0AS'	//回光返照
integer SPELL_SHITF_DEATHKNIGHT_D_CRAZY_DUOLUO = 'A0EB'				//堕落
//GOD
integer SPELL_SHITF_DEATHKNIGHT_Q_GOD_YUANQIZHAN = 'A0AH'		//怨气斩
integer SPELL_SHITF_DEATHKNIGHT_W_GOD_JIUSHU = 'A0AI'				//救赎
integer SPELL_SHITF_DEATHKNIGHT_E_GOD_FANKANGMINGYUN = 'A0AQ'	//反抗命运
integer SPELL_SHITF_DEATHKNIGHT_R_GOD_HUIGUANGFANZHAO = 'A0EA'	//回光返照
integer SPELL_SHITF_DEATHKNIGHT_D_GOD_DUOLUO = 'A0AY'				//堕落
//FIGHT



endglobals
